final!

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -22,41 +22,36 @@ runs:
   using: 'composite'
   steps:
     - run: |
-        echo "x: '${{ inputs.PR_title }}'"
+        ## 🚀🚀🚀
+        set +e  # This lets us handle non-zero exits
+
+        if [ -z "$(git status --porcelain)" ]; then
+          echo "ERROR: Oops! You need to make some changes before creating a pull request."
+          exit 1
+        fi
+
+        git config user.name "${{ inputs.git_name }}"
+        git config user.email "${{ inputs.git_email }}"
+
+        branch="action-create-PR-$(date +'%Y%m%d_%H%M%S')"
+        git checkout -b $branch
+
+        git add .
 
         ## Handle empty commit messages (as commits require messages)
-        msg=${{ inputs.PR_title }}
+        msg="${{ inputs.PR_title }}"
         if [ -z "$msg" ]; then
           msg="Review changes in $(git diff --cached --name-only | wc -l) files."
         fi
 
-        echo "xx: $msg"
+        git commit -m "$msg"
 
+        git push origin $branch
+
+        ## TODO: Find a way so users don't have to check the box in order to use this action
+        gh pr create -f
+        if [ $? -eq 1 ]; then
+          echo "ERROR: Oops! You need to allow GitHub Actions to create a PR by checking the checkbox 'Allow GitHub Actions to create and approve pull requests' at https://github.com/$GITHUB_REPOSITORY/settings/actions ."
+          exit 1
+        fi
       shell: bash
-    # - run: |
-    #     ## 🚀🚀🚀
-    #     set +e  # This lets us handle non-zero exits
-
-    #     if [ -z "$(git status --porcelain)" ]; then
-    #       echo "ERROR: Oops! You need to make some changes before creating a pull request."
-    #       exit 1
-    #     fi
-
-    #     git config user.name "${{ inputs.git_name }}"
-    #     git config user.email "${{ inputs.git_email }}"
-
-    #     branch="action-create-PR-$(date +'%Y%m%d_%H%M%S')"
-    #     git checkout -b $branch
-
-    #     git add .
-    #     git commit -m "${{ inputs.PR_title }}"
-
-    #     git push origin $branch
-
-    #     ## TODO: Find a way so users don't have to check the box in order to use this action
-    #     gh pr create -f
-    #     if [ $? -eq 1 ]; then
-    #       echo "ERROR: Oops! You need to allow GitHub Actions to create a PR by checking the checkbox 'Allow GitHub Actions to create and approve pull requests' at https://github.com/$GITHUB_REPOSITORY/settings/actions ."
-    #       exit 1
-    #     fi
-    #   shell: bash
