dev

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -53,7 +53,14 @@ runs:
         git push origin $branch
         echo "::endgroup::"
 
+        ## TODO: Find a way so users don't have to check the box in order to use this action
         echo "::group::DEBUG: do  gh pr create -f"
         gh pr create -f
+        if [ $? -eq 1 ]; then
+          echo "ERROR: Oops! You need to allow GitHub Actions to create a PR by checking \
+          the checkbox 'Allow GitHub Actions to create and approve pull requests' \
+          at https://github.com/OWNER/REPO/settings/actions."
+          exit 1
+        fi
         echo "::endgroup::"
       shell: bash
