dev

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -31,6 +31,10 @@ runs:
         git add .
         git commit -m "foo bar baz"
 
+        if [ $? -eq 1 ]; then
+          echo "ERROR: Oops! You need to make some changes before creating a pull request."
+        fi
+
         git push origin $branch
 
         gh pr create -f
